### ISSUE TITLE
[Bug] Getting Panic Error after 20 seconds into apple logo

### ISSUE THREAD

**Issue by aniruddha789** [AurelienAudero/i5-7400-EFI-by-Aure#12]
### What is your configuration ?

- CPU: i5 7400
- RAM: 8 GB
- Hard Disk: Seagate 512GB
- USB Boot drive - SanDisk 64 GB
- GPU: HD 630
- Additional infos:
- 

### Describe the Bug

Getting Panic Error after 20 seconds into apple logo

### Steps to Reproduce

After booting to opencore

### Anything else ?

Panic log attached
[panic-2022-12-31-220619.txt](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/files/10327968/panic-2022-12-31-220619.txt)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AurelienAudero** [comment]
Hi @aniruddha789,
Your issue appears to be iGPU related.

I have other questions to try to solve your problem :
- What is your motherboard ?
- How many screens do you have ?
- What video ports you use ?
- Is macOS already installed ?
- Does it crash while displaying the Apple Logo screen ?

Thanks

**Comment by aniruddha789** [comment]
![image](https://user-images.githubusercontent.com/41892662/210252969-57f37d23-53b4-4f28-acde-8a4118b505bb.png)
Hi, it worked after I replaced device properties in config.plist with the above.
My details
ASUS H110M-CS MOBO
Single screen 
VGA Monitor
macOS was not installed earlier
Yes it crashed while apple logo

Note: I also had multiple kexts for USB mapping which also was giving me further issues so I removed them all and just used USBports.kext

**Comment by AurelienAudero** [comment]
In your BIOS do you have an option to set the VRAM allocated to the iGPU, if so how is it set ?

Changing the setting in your BIOS rather than in your confit.plist (by using the stolenmem properties) improves stability and performance.

**Comment by aniruddha789** [comment]
In BIOS I have set dVMT to 64MB. Btw with the above settings I shared it boots fine but the VRAM shows only 3 MB in the about section. Also its laggy and unresponsive. What do you think would be the issue. I have tried changing SMBIOS from iMac18,1 to Macmini8,1 but no help. 
My EFI folder- https://drive.google.com/file/d/1r1-EJ1z0v86FofzxoB78nW156RIYSQ7V/view?usp=share_link

Note: Im using VGA port as my mobo doesnt have HDMI or DVI

**Comment by AurelienAudero** [comment]
Hi,
The graphics showing 3MB are because the iGPU fall back to VESA Drivers.
So there is no graphics acceleration, this means no transparency, very laggy animations and slow graphics.

But I think this problem can be resolved...
This may be an issue with the framebuffer or the video port that need to be patch.

I will investigate more deeply and suggest a patch for you when I find the time to do it.

Thanks again.

**Comment by aniruddha789** [comment]
Thanks for taking out time.

**Comment by AurelienAudero** [comment]
Hi,
Sorry for the long answer time.
First of all, set the DVMT to 128MB in the BIOS.
After that, download and boot from the first EFI linked to this message (called `EFI1.zip`) and tell me what happens.
If it does not boot or it boot with the VESA Drivers (you see 3MB in "About my Mac"), try the second EFI linked to this message (called `EFI2.zip`) and tell me what happens.

Thanks.

---

#### Important informations :
- All the EFIs linked to this message are modified versions of [the latest version of the EFI (with boot picker) at that time (v2.05)](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/releases/tag/2.05). These should be compatible with the stable versions of macOS Ventura 13.1, macOS Ventura 13.2 and macOS Ventura 13.2.1. **The compatibility of macOS Beta Softwares are not guaranteed.**
- I reused the same SMBIOS information that were in the EFI you sent me. So you don't need to change them for the moment but when macOS will be correctly installed, it's strongly recommended to change them because **you should never share** theses informations.

---

#### Download links :
[EFI1.zip](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/files/10888093/EFI1.zip)
[EFI2.zip](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/files/10888094/EFI2.zip)

**Comment by caicatar** [comment]
Hi, @AurelienAudero I'm also suffering from the same issue. I'm running with the same specification except for the fact that I'm using EX H110M-V instead of CS. The DVMT option is unavailable on H110M-V units so I can't really set the amount to allocate. 

I'm using the 2.05 EFI, here are what I've noticed:
1. Without "-igfxvesa", the ventura installer fails and gives me a panic error.  
2. With "-igfxvesa", the installer goes on a seemingly never-ending load screen and in verbose it repeats the same thing over and over ( sandbox restriction/bluetoothd not running ). 

Would you mind helping me with this? I already tried the EFI1 and EFI2 you have provided, to no avail.

**Comment by AurelienAudero** [comment]
Hi @caicatar,
It seems like there is a problem with H110 motherboards and this EFI.
I will investigate more into this issue, thanks for your informations.
I will come to you when I know more about it.

Thanks for using my EFI.
Aurélien

**Comment by caicatar** [comment]
> Hi @caicatar, It seems like there is a problem with H110 motherboards and this EFI. I will investigate more into this issue, thanks for your informations. I will come to you when I know more about it.
> 
> Thanks for using my EFI. Aurélien

This is noted. Hope it works soon. Thanks!

**Comment by AurelienAudero** [comment]
Hi everyone,
I apologize for the long delay. I was having exams and a lot of work.

It appears that H110 motherboards doesn't have the option to disable CFG-Lock in the BIOS which is necessary in order to use this EFI. So, I made a modified version of this EFI (based of the latest v2.06) which allows macOS to fonction properly with CFG-Lock on. You can download it [here](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/files/11556052/Intel_i5-7400_Hackintosh_EFI_H110_DEBUG.zip). Please let me know if it works.

**⚠️ Please note that this is only a test version as of now !**
_If it works, a definitive and more polished version will be available in [the Release section](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/releases)._

Thanks for your time and I apologize once again for the delay.
Aurélien.

**Comment by caicatar** [comment]
> Hi everyone, I apologize for the long delay. I was having exams and a lot of work.
> 
> It appears that H110 motherboards doesn't have the option to disable CFG-Lock in the BIOS which is necessary in order to use this EFI. So, I made a modified version of this EFI (based of the latest v2.06) which allows macOS to fonction properly with CFG-Lock on. You can download it [here](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/files/11556052/Intel_i5-7400_Hackintosh_EFI_H110_DEBUG.zip). Please let me know if it works.
> 
> **⚠️ Please note that this is only a test version as of now !** _If it works, a definitive and more polished version will be available in [the Release section](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/releases)._
> 
> Thanks for your time and I apologize once again for the delay. Aurélien.

Thanks @AurelienAudero, I'll make sure to test this one out and I'll give you a feedback once I'm done.

**Comment by AurelienAudero** [comment]
Hi @caicatar,
Can you give me a feedback ?

Thanks.
Aurélien.

**Comment by AurelienAudero** [comment]
Hi,
As I no longer have an answer, I will now close this thread.
If necessary, I invite you to open another issue.

Thanks.
Aurélien.
