### ISSUE TITLE
[BUG] - Bloqué dans le logo Apple 

### ISSUE THREAD

**Issue by mortadhaghaliounji** [AurelienAudero/i5-7400-EFI-by-Aure#22]
### Quel est votre configuration ?

- CPU : i5-7400
- Carte mère : H110 Chipset LPC
- RAM : 8GB Ram
- Disque Dur : Segate ST100DM003-1SB1
- GPU : Intel HD Graphics 630
- ISO : Ventura 13.3m
- Infos Additionnelles :
      - J'ai usé du EFI fourni pour éviter le problème avec le CFG-lock.

### Décrivez le bug

![IMG_20230620_160816](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/assets/51703175/900cfbc4-a9c6-460c-8447-24cbd726bc44)
[IMAGE du BUG]

Je boot dans mon installation normalement, le logo Apple apparaît avec la bar de progression qui avance de plus en plus lentement, après plus de 10min, elle semble être devenu immobile, j'attends près de 4h rien ne change. 

### Étapes pour le reproduire

1. Je boot sur ma clé usb
2. Je sélectionne "Install Ventura"
3. Le logo Apple apparaît
4. La bar de progression apparaît
5. Elle s'arrête après 40-50%

### Je vérifie mon formulaire

- [X] J'ai bien spécifié un titre en rapport avec mon problème
- [X] Mon titre commence par "[Bug]" (sans les guillemets)

### Code de Conduite

- [X] J'accepte de suivre le code de conduite de ce projet

**Comment by AurelienAudero** [comment]
Hi @hepestos
It appears that there is an error that prevent your system from booting into macOS installer.

In order to help you fix this issue, I will need you to activate verbose mode.
To do this, you will need to edit your EFI. Once you opened your `config.plist` in ProperTree, go into `NVRAM -> Add -> 7C436110-AB2A-4BBB-A880-FE41995C9F82`and then add `-v` at the beginning of the `boot-args` thing.

After that, save and close your file, then reboot with the EFI you just modified. This time, there will be a lot of scrolling text on the screen, don’t worry, this will help me know which part of the startup process is causing an issue.

Once the text has stopped scrolling for a little while, take a picture of the entire screen (make sure it is readable) and then attach it to your reply. This way, I will be able to help you fix your problem.

Thanks for using my EFI.
Aurélien.

**Comment by AurelienAudero** [comment]
Bonjour @hepestos
On dirait qu’il y a une erreur qui vous empêche de démarrer l’installateur macOS.

Afin de vous aider à résoudre ce problème, j'aurai besoin que vous activiez le mode verbose.
Pour cela, vous devez modifier votre EFI. Une fois que vous avez ouvert votre `config.plist` dans ProperTree, aller dans `NVRAM -> Add -> 7C436110-AB2A-4BBB-A880-FE41995C9F82`puis ajouter `-v` au début de la section `boot-args`.

Après cela, enregistrez et fermez votre fichier, puis redémarrez avec l'EFI que vous venez de modifier. Cette fois, il y aura beaucoup de texte qui va défiler à l'écran, ne vous inquiétez pas, cela m'aidera à savoir quelle partie du processus de démarrage est à l'origine du problème.

Une fois que le texte a cessé de défiler pendant un certain temps, prenez une photo de l'ensemble de l'écran (assurez-vous que le texte sur la photo est lisible), puis joignez-le à votre réponse. De cette façon, je serai en mesure de vous aider à résoudre votre problème.

Merci d’utiliser mon EFI.
Aurélien.

**Comment by mortadhaghaliounji** [comment]
Bonjour, merci de ta réponse.

![IMG_20230621_185415.jpg](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/assets/51703175/27a9aca8-0f73-4216-b4c8-5c44a49185af)

L'installation semble ce bloqué à ce stade.
