### ISSUE TITLE
[Bug] Displaypolicyd error on UHD 630

### ISSUE THREAD

**Issue by Bendy3192** [AurelienAudero/i5-7400-EFI-by-Aure#31]
### What is your configuration ?

- CPU: i5-7400
- Motherboard : ASUS B250M-K
- RAM: 16GB
- Hard Disk: 512GB nvme, WD
- GPU: intel UHD 630
- Additional infos:

### Describe the Bug

At first, when I succesfully booted Mac OS Sonoma (no smbios error), my pc after about 20 seconds goes reboot. Before I had problems with lilu.kext, so, i removed lilu. Now my Sonoma boot stuck at something like on this photo (sorry for img intead of normal .log)
![IMG_20231211_224334](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/assets/104999566/7129b6fb-bef5-41b9-9c00-f929111b3db6)
On Ventura same situation and I don't understand what's wrong (before Ventura worked very well on clover, but now on clover same situation.) I used Macmini8,1 SMBIOS and it works on apple coverage website. I allocated gpu memory 128MB (or higher), but doesn't works. And also I set almost all options from guide in my bios, but.. The problem is in place.

P.S. MAC also used as Generic > ROM

### Steps to Reproduce

1. I boot to OpenCore
2. I select Mac OS Sonoma installation
3. Stuck at displaypolicyd error.

### I'm checking my form

- [X] I have specified a title related to my problem
- [x] My title starts with "[Bug]" (without the quotes)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AurelienAudero** [comment]
Hi @Bendy3192,
There seem to be some issues in your EFI configuration :

---

> Before I had problems with lilu.kext, so, i removed lilu.

Lilu and Whatevergreen are very important kexts, the issue you're having is probably due to the fact that Lilu is missing in your EFI.

---

> I used Macmini8,1 SMBIOS and it works on apple coverage website.

What do you mean by "works on apple coverage website" ?
You don't want to use the SMBIOS of a real Mac. As said in step 5 of the "[Setup the SMBIOS](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/tree/3.07#setup-the-smbios)" section of the README :

> 5. Check the generated serial number on [Apple Check Coverage](https://checkcoverage.apple.com/). You want to get this message back : "We’re sorry, we’re unable to check coverage for this serial number". If you don't get it, you need to regenerate another serial.

---

> MAC also used as Generic > ROM

What value did you used here ? The `Apple ROM` part of GenSMBIOS or the MAC address of your network interface ?

---

The EFI has also been updated today to support macOS Sonoma 14.2.
So, I invite you to update your EFI to the latest release available.

Thanks for using my EFI.
Aurélien.

---

**⚠️ Next time, please follow ALL of the instructions listed under "I'm checking my form" before submitting your issue. This helps other people navigate the issues list.**
_You did not follow the following rule : `My title starts with "[Bug]" (without the quotes)`_

**Comment by Bendy3192** [comment]
@AurelienAudero I'm sorry, I misunderstood the guide. Okay, I'll try to change the SMBIOS, but I also had some kind of problem with the bluetoothd service, although I don't have it at all. The problem was in apple key store bluetoothd service. Were all the problems in the wrong SMBIOS? In Generic > ROM I've entered my MAC address in lowercase without ":" symbol.

Thanks!

UPD: Now I've trying again and I can't boot into gui with -igfxvesa and with igfxonln=1 rebooting after 20 seconds automatically. Last messages with vesa look like this:

![photo_2023-12-13_12-45-02](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/assets/104999566/2bb9069a-aaf7-46f5-b196-b788650fd316)

Monitor -- DVI-D

**Comment by AurelienAudero** [comment]
Hi @Bendy3192,

---

> I also had some kind of problem with the bluetoothd service, although I don't have it at all.


The bluetoothd service is a macOS system service that runs even if you don't have Bluetooth on your system.

---

>  I've entered my MAC address in lowercase without ":" symbol.


Perfect.

---

> I can't boot into gui with -igfxvesa


What happen when you try without adding `-igfxvesa` ?

---

I saw that you are using a NVMe Drive, so you may want to update your EFI to the latest version because the new update improves stability and performance with NVMe Drives.

Thanks for using my EFI.
Aurélien.

**Comment by AurelienAudero** [comment]
Hi @Bendy3192,
Since this issue has been inactive for a while now, It will close automatically in 7 days if no new message is sent.
If you still need help, I invite you to send another message here and give details on the progress of the issue before 00:00 on February 25, 2024 (Central European Time). After this date, you will need to open a new issue by clicking [here](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/issues/new/choose).

Thanks.
Aurélien.

**Comment by Bendy3192** [comment]
Hello @AurelienAudero. I apologize for the long absence, but I still can't boot even with -igfxvesa. Last error in cycle related to GUI, it just can't boot into setup.
![PXL_20240324_212014516](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/assets/104999566/dab77bde-425b-4a93-a3ad-c01a00543dc4)
![PXL_20240324_211957971](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/assets/104999566/4515627c-4a2f-4caa-846d-0d555a5b81c4)

**Comment by AurelienAudero** [comment]
This issue has been closed for inactivity and its creator has recently opened another issue to continue resolving it.
The continuation of this issue is available at #39.
