### ISSUE TITLE
[Question] Can I use my GTX 750Ti with UHD 630 to get work DRM?

### ISSUE THREAD

**Issue by Bendy3192** [AurelienAudero/i5-7400-EFI-by-Aure#32]
### What is your question ?

I read right now about DRM is broken, so, can I use my intel UHD 630 with my Macmini8,1 SMBIOS for Mac OS, and Nvidia for just displaying video on monitor? In this way bios settings like in README.md, or I need to change some options, like for example initialize iGPU Multi-Monitor?

### Anything else ?

Huge thanks for the support

### I'm checking my form

- [X] My question is not about a bug or issue I have using this EFI (if so, I use the form named "Bug/Issue Report")
- [X] I have specified a title related to my problem
- [X] My title starts with "[Question]" (without the quotes)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AurelienAudero** [comment]
Hi @Bendy3192,
The GTX 750Ti requires NVIDIA Web Drivers in order to work with macOS but the last version of macOS currently supporting NVIDIA Web Drivers is macOS High Sierra 10.13.6.
So you won't be able to use your GTX 750Ti on newer versions of macOS (Mojave and earlier).
To get a working macOS setup, you can instead use your UHD 630 graphics and disable your NVIDIA GPU in the BIOS.

---

I leave this issue open in case you have other questions.
If I have answered all your questions, I invite you to close it, else it will be closed and marked as resolved automatically in 7 days.

---

Thanks for using my EFI.
Aurélien.

---

**⚠️ Next time, please follow ALL of the instructions listed under "I'm checking my form" before submitting your issue. This helps other people navigate the issues list.**
_You did not follow the following rule : `My title starts with "[Question]" (without the quotes)`_
