### ISSUE TITLE
[Bug] Download Link Invalid

### ISSUE THREAD

**Issue by dotfrankruan** [AurelienAudero/i5-7400-EFI-by-Aure#37]
### What is your configuration ?
_Not applicable_

### Describe the Bug
Hello, the download link appears to be invalid at the time of writing, please fix it. Thanks. 

### Steps to Reproduce
1. Go to the ["Make the Installation USB" section of the README](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/blob/master/README.md#make-the-installation-usb)
2. Click on the link to download macOS Sonoma

### I'm checking my form
- [X] I have specified a title related to my problem
- [X] My title starts with "[Bug]" (without the quotes)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AurelienAudero** [comment]
Hi @orange2008,
You didn't use the proper issue template to create this issue, you should have used the "Bug/Issue Report (English)" option.
It's okay for this time but please try to choose the correct one if you need to open another issue in the future.
So I updated the labels and title of this issue, as well as your message accordingly.

In order to help you resolve this issue, I need you to complete the `Steps to Reproduce` section of your message.
After a quick first investigation, the download links appears to be working, so I really need more precision to help you.

Thanks for using my EFI.
Aurélien.

**Comment by dotfrankruan** [comment]
> Hi @orange2008, You didn't use the proper issue template to create this issue, you should have used the "Bug/Issue Report (English)" option. It's okay for this time but please try to choose the correct one if you need to open another issue in the future. So I updated the labels and title of this issue, as well as your message accordingly.
> 
> In order to help you resolve this issue, I need you to complete the `Steps to Reproduce` section of your message. After a quick first investigation, the download links appears to be working, so I really need more precision to help you.
> 
> Thanks for using my EFI. Aurélien.

The link [https://www.mediafire.com/file/wio1f0s9e8bzyiw/Olarila+Sonoma.raw/file](https://www.mediafire.com/file/wio1f0s9e8bzyiw/Olarila+Sonoma.raw/file) is not valid.
Once I opened it, it redirected to the error page.

**Comment by AurelienAudero** [comment]
Hi @orange2008,
Indeed, the link doesn't seem to work. Thank you for informing me about this.
I updated it so you are now able to download the latest version of macOS.

Thanks for using my EFI.
Aurélien.
