### ISSUE TITLE
[Bug] Can't run into GUI fullscreen at first boot

### ISSUE THREAD

**Issue by Bendy3192** [AurelienAudero/i5-7400-EFI-by-Aure#39]
### What is your configuration ?

- CPU: i5-7400
- Motherboard : ASUS B250M-K
- RAM: 16 GB
- Hard Disk: WD 512GB
- GPU: UHD 630
- Additional infos:
At same SSD I recently booted in Sonoma/Ventura. But now I can't

### Describe the Bug

I used yo EFI with my MAC and I generated smbios. But I still can't boot even with -igfxvesa. Last error in cycle related to GUI, it just can't boot into fullscreen setup

![PXL_20240324_211957971](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/assets/104999566/d544f5a2-f4a1-46d1-8f59-3dd64818fe5d)
![PXL_20240324_212014516](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/assets/104999566/bed239df-cff8-4686-9353-65d2e3f03641)

### Steps to Reproduce

1. I boot to OpenCore
2. I select MacOS option
3. Wait about minute, then I've got GUI fullscreen error, which in cycle.

### I'm checking my form

- [X] I have specified a title related to my problem
- [X] My title starts with "[Bug]" (without the quotes)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AurelienAudero** [comment]
Hi @Bendy3192,
Sorry for the late answer, I had a lot of work to do lately.
I didn't I asked you about your UEFI settings. Did you follow carefully the instructions [here](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI?tab=readme-ov-file#setup-the-bios) ?
Were you able to find all of the options listed in the guide ? If not, it may be the cause of the issue.

Thanks for using my EFI.
Aurélien.

**Comment by AurelienAudero** [comment]
#31

**Comment by Bendy3192** [comment]
![IMG_1463](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/assets/104999566/2b17c4ac-1e77-43b0-bc20-a19ab557c1ee)

@AurelienAudero Hello again. I've trying to boot again. Now with Sonoma 14.5 but wit -v and -igfxvesa I have endless cycled screen without GUI. I've tried igfxonln=1 and vesa, but always reboot or endless loading. All bios settings (including UEFI) were edited like in example. I'm using dvi-d.

**Comment by AurelienAudero** [comment]
Hi @Bendy3192, could you try adding `-igfxmlr` into `boot-args` ?

**Comment by AurelienAudero** [comment]
Hi @Bendy3192,
Since this issue has been inactive for a while now, It will close automatically in 7 days if no new message is sent.
If you still need help, I invite you to send another message here and give details on the progress of the issue before 00:00 on September 23, 2024 (Central European Time). **After this date, you will no longer be able to open a new issue since this project is no longer maintained since September 8, 2024 and official support has ended.**

_You can learn more about the end of support [here](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/blob/master/README.md)._

Thanks.
Aurélien.

**Comment by AurelienAudero** [comment]
This issue has been closed for inactivity.
No further support will be provided for this issue.
